# Generated by Django 4.1 on 2023-04-17 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobinfo',
            name='category',
            field=models.CharField(choices=[('bcs', 'BCS'), ('nationalized', 'Nationalized'), ('10% quota', '10% quota'), ('non govt.', 'Non Govt.')], max_length=45, null=True),
        ),
    ]
